(YUVA) Adding some error handling to the PR creation

diff --git a/scripts/security-updates/automatic-update b/scripts/security-updates/automatic-update
--- a/scripts/security-updates/automatic-update
+++ b/scripts/security-updates/automatic-update
@@ -126,17 +126,30 @@ if [[ $(security_updates_available) == "true" ]]; then
     fi
     PARAMETERS=$(printf '{"title":"%s","body":"%s","head":"%s","base":"%s"}' "$TITLE" "${BODY//$'\n'/\\n}" "$BRANCH_NAME" "$CIRCLE_BRANCH")
 
-    # Running the request
-    curl -o /dev/null -L \
-    -X POST \
-    -H "Accept: application/vnd.github+json" \
-    -H "Authorization: Bearer $GITHUB_TOKEN" \
-    -H "X-GitHub-Api-Version: 2022-11-28" \
-    https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls \
-    -d "$PARAMETERS"
+    # creating PR.
+    response=$( \
+        curl -sw "%{http_code}" -L \
+        -X POST \
+        -H "Accept: application/vnd.github+json" \
+        -H "Authorization: Bearer $GITHUB_TOKEN" \
+        -H "X-GitHub-Api-Version: 2022-11-28" \
+        https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls \
+        -d "$PARAMETERS" \
+    )
 
-    echo "Pull request: $TITLE successfully created."
-    echo "-------------------------------------------"
+    # Extracting the HTTP status code from the response
+    http_status="${response: -3}"
+
+    if [ "$http_status" == "200" -o "$http_status" == "201" ]; then
+      echo "Pull request: $TITLE successfully created."
+      echo "-------------------------------------------"
+    else
+      echo "Failed to create pull request: $TITLE. HTTP status code: $http_status"
+      echo "-------------------------------------------"
+      exit 1
+    fi
+
+
 
     echo "Creating security updates Zendesk Ticket."
     echo "-------------------------------------------"
